from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build an editor export package from AI4Video output directories and a chosen experience template."
    )
    parser.add_argument(
        "--materials",
        nargs="+",
        required=True,
        help="One or more AI4Video output directories containing step1/step2/step3 JSON files.",
    )
    parser.add_argument(
        "--videos",
        nargs="+",
        required=True,
        help="One or more source video paths corresponding to --materials in the same order.",
    )
    parser.add_argument(
        "--experience",
        required=True,
        help="Path to the chosen elastic_template.json used as editingExperience.",
    )
    parser.add_argument(
        "--workspace-id",
        default="workspace_ai4video_trial",
        help="Workspace id to embed in the package.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output path for the generated *.editing-package.json.",
    )
    parser.add_argument(
        "--timeline-plan",
        default=None,
        help="Optional timeline_plan.json generated by an editing planner. If omitted, a simple rule-based plan is generated.",
    )
    parser.add_argument(
        "--planner-info",
        default=None,
        help="Optional planner metadata JSON to embed in the package.",
    )
    parser.add_argument(
        "--max-video-clips-per-material",
        type=int,
        default=None,
        help="Optional cap for how many visual shots to keep per material.",
    )
    parser.add_argument(
        "--max-duration-ms",
        type=int,
        default=None,
        help="Optional cap for per-material duration. Clips and subtitles outside this window are dropped.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if len(args.materials) != len(args.videos):
        raise SystemExit("--materials and --videos must have the same number of items.")

    experience = _load_editing_experience(Path(args.experience).expanduser().resolve())

    source_materials = []
    source_assets = []

    cumulative_offset_ms = 0
    render_width = 1080
    render_height = 1920

    for material_index, (material_dir_raw, video_raw) in enumerate(zip(args.materials, args.videos), start=1):
        material_dir = Path(material_dir_raw).expanduser().resolve()
        video_path = Path(video_raw).expanduser().resolve()
        source_key = material_dir.name
        source_material = _load_source_material(
            material_dir=material_dir,
            source_key=source_key,
            max_video_clips_per_material=args.max_video_clips_per_material,
            max_duration_ms=args.max_duration_ms,
        )
        source_materials.append(source_material)

        width, height, duration_seconds, size_bytes = _probe_video(video_path)
        if material_index == 1 and width and height:
            render_width, render_height = width, height

        asset = {
            "assetId": f"asset_source_{material_index}",
            "workspaceId": args.workspace_id,
            "category": "VIDEO",
            "slot": "SOURCE",
            "origin": "DESKTOP",
            "storageMode": "LOCAL",
            "syncStatus": "READY",
            "name": video_path.name,
            "mimeType": "video/mp4",
            "sizeBytes": size_bytes,
            "addedAt": datetime.now(timezone.utc).isoformat(),
            "durationSeconds": duration_seconds,
            "frameWidth": width,
            "frameHeight": height,
            "objectUrl": str(video_path),
        }
        source_assets.append(asset)

        cumulative_offset_ms += source_material["durationMs"]

    timeline_id = f"timeline_{args.workspace_id}_{experience['styleId']}_{len(source_assets)}_{len(source_materials)}"
    editing_job_id = f"editing_job_{timeline_id}"
    timeline_plan = _load_planner_timeline_plan(
        timeline_plan_path=Path(args.timeline_plan).expanduser().resolve() if args.timeline_plan else None,
        fallback_timeline_id=timeline_id,
        workspace_id=args.workspace_id,
        experience=experience,
        source_assets=source_assets,
        source_materials=source_materials,
        target_duration_ms=cumulative_offset_ms,
    )
    planner_info = _load_planner_info(Path(args.planner_info).expanduser().resolve() if args.planner_info else None)

    export_package = {
        "exportedAt": datetime.now(timezone.utc).isoformat(),
        "sourceAssets": source_assets,
        "sourceMaterials": source_materials,
        "editingExperience": experience,
        "timelinePlan": timeline_plan,
        "editingJob": {
            "jobId": editing_job_id,
            "timelineId": timeline_plan["timelineId"],
            "renderer": "hyperframes",
            "status": "draft",
            "compositionPath": f"ai-service/output/plans/{timeline_plan['timelineId']}.hyperframes/",
            "outputPath": f"ai-service/output/renders/{timeline_plan['timelineId']}.final.mp4",
            "renderHints": {
                "fps": 30,
                "width": render_width,
                "height": render_height,
                "format": "mp4",
            },
        },
        "renderResult": {
            "renderId": f"render_{editing_job_id}",
            "jobId": editing_job_id,
            "status": "not_started",
            "outputPath": f"ai-service/output/renders/{timeline_plan['timelineId']}.final.mp4",
            "previewAssetId": source_assets[0]["assetId"] if source_assets else None,
        },
    }
    if planner_info:
        export_package["planner"] = planner_info

    output_path = Path(args.output).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(export_package, indent=2, ensure_ascii=False), encoding="utf-8")
    print(output_path)


def _load_planner_timeline_plan(
    *,
    timeline_plan_path: Path | None,
    fallback_timeline_id: str,
    workspace_id: str,
    experience: dict,
    source_assets: list[dict],
    source_materials: list[dict],
    target_duration_ms: int,
) -> dict:
    if timeline_plan_path is not None:
        plan = json.loads(timeline_plan_path.read_text(encoding="utf-8"))
        if "timelinePlan" in plan:
            plan = plan["timelinePlan"]
        return _normalize_timeline_plan(
            plan=plan,
            fallback_timeline_id=fallback_timeline_id,
            workspace_id=workspace_id,
            experience=experience,
            source_assets=source_assets,
            source_materials=source_materials,
            target_duration_ms=target_duration_ms,
        )

    return _build_rule_based_timeline_plan(
        timeline_id=fallback_timeline_id,
        workspace_id=workspace_id,
        experience=experience,
        source_assets=source_assets,
        source_materials=source_materials,
    )


def _load_planner_info(planner_info_path: Path | None) -> dict | None:
    if planner_info_path is None or not planner_info_path.exists():
        return None
    return json.loads(planner_info_path.read_text(encoding="utf-8"))


def _normalize_timeline_plan(
    *,
    plan: dict,
    fallback_timeline_id: str,
    workspace_id: str,
    experience: dict,
    source_assets: list[dict],
    source_materials: list[dict],
    target_duration_ms: int,
) -> dict:
    valid_asset_ids = {asset["assetId"] for asset in source_assets}
    valid_material_ids = {material["sourceMaterialId"] for material in source_materials}
    tracks_by_type = {
        "video": {"trackId": "track_video_main", "type": "video", "clips": []},
        "subtitle": {"trackId": "track_caption_main", "type": "subtitle", "clips": []},
        "overlay": {"trackId": "track_overlay_main", "type": "overlay", "clips": []},
        "audio": {"trackId": "track_audio_main", "type": "audio", "clips": []},
    }

    for track in plan.get("tracks", []):
        track_type = track.get("type")
        if track_type not in tracks_by_type:
            continue
        for raw_clip in track.get("clips", []):
            clip = _normalize_clip(raw_clip, track_type)
            if clip is None:
                continue
            if track_type == "video":
                if clip.get("assetId") not in valid_asset_ids:
                    continue
                if clip.get("sourceMaterialId") not in valid_material_ids:
                    continue
            elif clip.get("sourceMaterialId") and clip.get("sourceMaterialId") not in valid_material_ids:
                continue
            tracks_by_type[track_type]["clips"].append(clip)

    if not tracks_by_type["video"]["clips"]:
        return _build_rule_based_timeline_plan(
            timeline_id=fallback_timeline_id,
            workspace_id=workspace_id,
            experience=experience,
            source_assets=source_assets,
            source_materials=source_materials,
        )

    for track in tracks_by_type.values():
        track["clips"].sort(key=lambda clip: int(clip.get("startMs", 0)))

    computed_duration_ms = max(
        int(clip.get("startMs", 0)) + int(clip.get("durationMs", 0))
        for clip in tracks_by_type["video"]["clips"]
    )
    return {
        "timelineId": str(plan.get("timelineId") or fallback_timeline_id),
        "workspaceId": str(plan.get("workspaceId") or workspace_id),
        "styleId": str(plan.get("styleId") or experience["styleId"]),
        "sourceAssetIds": [asset["assetId"] for asset in source_assets],
        "sourceMaterialIds": [material["sourceMaterialId"] for material in source_materials],
        "targetDurationMs": max(1000, int(plan.get("targetDurationMs") or computed_duration_ms or target_duration_ms)),
        "tracks": [
            tracks_by_type["video"],
            tracks_by_type["subtitle"],
            tracks_by_type["overlay"],
            tracks_by_type["audio"],
        ],
    }


def _normalize_clip(raw_clip: dict, track_type: str) -> dict | None:
    try:
        start_ms = max(0, int(raw_clip.get("startMs", 0)))
        duration_ms = max(100, int(raw_clip.get("durationMs", 0)))
    except (TypeError, ValueError):
        return None

    clip = {
        "clipId": str(raw_clip.get("clipId") or f"clip_{track_type}_{start_ms}"),
        "type": track_type,
        "startMs": start_ms,
        "durationMs": duration_ms,
        "label": str(raw_clip.get("label") or track_type),
    }
    if raw_clip.get("assetId"):
        clip["assetId"] = str(raw_clip["assetId"])
    if raw_clip.get("sourceMaterialId"):
        clip["sourceMaterialId"] = str(raw_clip["sourceMaterialId"])
    if raw_clip.get("sourceStartMs") is not None:
        try:
            clip["sourceStartMs"] = max(0, int(raw_clip["sourceStartMs"]))
        except (TypeError, ValueError):
            clip["sourceStartMs"] = 0
    if raw_clip.get("phaseId"):
        clip["phaseId"] = str(raw_clip["phaseId"])
    return clip


def _build_rule_based_timeline_plan(
    *,
    timeline_id: str,
    workspace_id: str,
    experience: dict,
    source_assets: list[dict],
    source_materials: list[dict],
) -> dict:
    timeline_tracks = {
        "video": {"trackId": "track_video_main", "type": "video", "clips": []},
        "subtitle": {"trackId": "track_caption_main", "type": "subtitle", "clips": []},
        "overlay": {"trackId": "track_overlay_main", "type": "overlay", "clips": []},
        "audio": {"trackId": "track_audio_main", "type": "audio", "clips": []},
    }
    cumulative_offset_ms = 0

    for material_index, (source_material, asset) in enumerate(zip(source_materials, source_assets), start=1):
        source_key = source_material["sourceCaseId"]
        for shot_index, shot in enumerate(source_material["visualShots"], start=1):
            timeline_tracks["video"]["clips"].append(
                {
                    "clipId": f"clip_video_{material_index}_{shot_index}",
                    "assetId": asset["assetId"],
                    "sourceMaterialId": source_material["sourceMaterialId"],
                    "type": "video",
                    "startMs": cumulative_offset_ms + shot["startMs"],
                    "durationMs": max(1000, shot["endMs"] - shot["startMs"]),
                    "sourceStartMs": shot["startMs"],
                    "label": f"{asset['name']} · {shot['shotType']}",
                }
            )

        for sentence_index, sentence in enumerate(source_material["transcript"]["sentences"], start=1):
            timeline_tracks["subtitle"]["clips"].append(
                {
                    "clipId": f"clip_caption_{material_index}_{sentence_index}",
                    "sourceMaterialId": source_material["sourceMaterialId"],
                    "type": "subtitle",
                    "startMs": cumulative_offset_ms + sentence["startMs"],
                    "durationMs": max(400, sentence["endMs"] - sentence["startMs"]),
                    "label": sentence["text"],
                }
            )

        overlay_index = 0
        for shot in source_material["visualShots"]:
            if shot["editingUtility"] not in {"HOOK_OPENER", "EMPHASIS_HIGHLIGHT"}:
                continue
            overlay_index += 1
            timeline_tracks["overlay"]["clips"].append(
                {
                    "clipId": f"clip_overlay_{material_index}_{overlay_index}",
                    "sourceMaterialId": source_material["sourceMaterialId"],
                    "type": "overlay",
                    "startMs": cumulative_offset_ms + shot["startMs"],
                    "durationMs": max(1000, shot["endMs"] - shot["startMs"]),
                    "label": f"{source_key} · {shot['editingUtility']}",
                }
            )

        for drop_index, drop_ms in enumerate(source_material["dropsMs"], start=1):
            timeline_tracks["audio"]["clips"].append(
                {
                    "clipId": f"clip_audio_{material_index}_{drop_index}",
                    "sourceMaterialId": source_material["sourceMaterialId"],
                    "type": "audio",
                    "startMs": cumulative_offset_ms + drop_ms,
                    "durationMs": 1000,
                    "label": f"{source_key} · Drop {drop_index}",
                }
            )

        cumulative_offset_ms += source_material["durationMs"]

    return {
        "timelineId": timeline_id,
        "workspaceId": workspace_id,
        "styleId": experience["styleId"],
        "sourceAssetIds": [asset["assetId"] for asset in source_assets],
        "sourceMaterialIds": [material["sourceMaterialId"] for material in source_materials],
        "targetDurationMs": cumulative_offset_ms,
        "tracks": [
            timeline_tracks["video"],
            timeline_tracks["subtitle"],
            timeline_tracks["overlay"],
            timeline_tracks["audio"],
        ],
    }


def _load_editing_experience(template_path: Path) -> dict:
    template = json.loads(template_path.read_text(encoding="utf-8"))
    metadata = template.get("style_metadata", {})
    style_id = metadata.get("style_id", "mock-style")
    return {
        "experienceId": f"mock_{style_id}",
        "styleId": style_id,
        "category": metadata.get("category", "UNKNOWN"),
        "styleName": " ".join(part.capitalize() for part in style_id.split("-") if part),
        "pacingStyle": metadata.get("pacing_style", "UNKNOWN"),
        "visualTheme": metadata.get("visual_theme", "UNKNOWN"),
        "tags": metadata.get("tags", []),
        "sampleVideoDurationMs": metadata.get("sample_video_total_duration_ms", 0),
        "storylinePhases": [
            {
                "phaseId": phase.get("phase_id", "PHASE_UNKNOWN"),
                "narrativeGoal": phase.get("narrative_goal", ""),
                "startMs": phase.get("absolute_time_range", {}).get("start_ms", 0),
                "endMs": phase.get("absolute_time_range", {}).get("end_ms", 0),
                "durationMs": phase.get("absolute_time_range", {}).get("duration_ms", 0),
            }
            for phase in template.get("storyline_structure", [])
        ],
        "dynamicBeatCount": len(template.get("dynamic_pacing_blueprint", [])),
    }


def _load_source_material(
    material_dir: Path,
    source_key: str,
    max_video_clips_per_material: Optional[int] = None,
    max_duration_ms: Optional[int] = None,
) -> dict:
    audio = json.loads((material_dir / "step1_audio.json").read_text(encoding="utf-8"))
    transcript = json.loads((material_dir / "step2_transcript.json").read_text(encoding="utf-8"))
    visual = json.loads((material_dir / "step3_visual.json").read_text(encoding="utf-8"))
    style_hints = {}
    elastic_path = material_dir / "elastic_template.json"
    if elastic_path.exists():
        style_hints = json.loads(elastic_path.read_text(encoding="utf-8"))

    visual_shots = [
        {
            "index": shot.get("index", 0),
            "startMs": shot.get("start_ms", 0),
            "endMs": shot.get("end_ms", 0),
            "shotType": shot.get("shot_type", "UNKNOWN"),
            "contentType": shot.get("content_type", "UNKNOWN"),
            "emotionalTone": shot.get("emotional_tone", "UNKNOWN"),
            "semanticPrompt": shot.get("b_roll_semantic_prompt", ""),
            "cameraMotionEffect": shot.get("camera_motion_effect", "UNKNOWN"),
            "editingUtility": shot.get("editing_utility", "UNKNOWN"),
        }
        for shot in visual.get("shots", [])
    ]
    if max_duration_ms is not None:
        visual_shots = [shot for shot in visual_shots if shot["startMs"] < max_duration_ms]
        if visual_shots:
            visual_shots = [{**shot, "endMs": min(shot["endMs"], max_duration_ms)} for shot in visual_shots]
    if max_video_clips_per_material is not None:
        visual_shots = visual_shots[: max(0, max_video_clips_per_material)]

    transcript_sentences = [
        {
            "text": sentence.get("text", ""),
            "startMs": sentence.get("start_ms", 0),
            "endMs": sentence.get("end_ms", 0),
        }
        for sentence in transcript.get("sentences", [])
    ]
    if max_duration_ms is not None:
        transcript_sentences = [
            {**sentence, "endMs": min(sentence["endMs"], max_duration_ms)}
            for sentence in transcript_sentences
            if sentence["startMs"] < max_duration_ms
        ]

    beats_ms = audio.get("beats_ms", [])
    drops_ms = audio.get("drops_ms", [])
    if max_duration_ms is not None:
        beats_ms = [beat for beat in beats_ms if beat < max_duration_ms]
        drops_ms = [drop for drop in drops_ms if drop < max_duration_ms]

    duration_ms = audio.get("duration_ms", 0)
    if max_duration_ms is not None:
        duration_ms = min(duration_ms, max_duration_ms)

    return {
        "sourceMaterialId": f"source_material_{source_key}",
        "sourceCaseId": source_key,
        "durationMs": duration_ms,
        "bpm": audio.get("bpm", 0),
        "beatsMs": beats_ms,
        "dropsMs": drops_ms,
        "transcript": {
            "fullText": transcript.get("full_text", ""),
            "sentences": transcript_sentences,
        },
        "visualShots": visual_shots,
        "optionalStyleHints": {
            "styleId": style_hints.get("style_metadata", {}).get("style_id"),
            "storylinePhaseCount": len(style_hints.get("storyline_structure", [])),
            "narrativeGoals": [
                phase.get("narrative_goal", "")
                for phase in style_hints.get("storyline_structure", [])
                if phase.get("narrative_goal")
            ],
        },
    }


def _probe_video(video_path: Path) -> tuple[int, int, float, int]:
    ffprobe_bin = _resolve_ffprobe_bin()
    command = [
        ffprobe_bin,
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=width,height:format=duration,size",
        "-of",
        "json",
        str(video_path),
    ]
    process = subprocess.run(command, capture_output=True, text=True, check=False)
    if process.returncode != 0:
        return 1080, 1920, 0.0, 0

    payload = json.loads(process.stdout)
    stream = (payload.get("streams") or [{}])[0]
    format_info = payload.get("format", {})
    return (
        int(stream.get("width", 1080)),
        int(stream.get("height", 1920)),
        float(format_info.get("duration", 0.0)),
        int(float(format_info.get("size", 0))),
    )


def _resolve_ffprobe_bin() -> str:
    env_bin = os.environ.get("CAPCUTAI_FFPROBE_BIN") or os.environ.get("FFPROBE_BIN")
    if env_bin:
        return str(Path(env_bin).expanduser())

    macos_full_bin = Path("/opt/homebrew/opt/ffmpeg-full/bin/ffprobe")
    if macos_full_bin.exists():
        return str(macos_full_bin)

    return shutil.which("ffprobe") or "ffprobe"


if __name__ == "__main__":
    main()
